apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    app: flask
spec:
  ports:
  - name: http
    port: 5000
  selector:
    app: flask

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: flask
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - image: mateobur/hello-flask
        name: flask
        ports:
        - containerPort: 5000
